### ISSUE TITLE
Error "Unhandled: Unexpected token" [1.0.4]

### ISSUE THREAD

**Issue by Gakk** [damienaicheh/azure-devops-launch-icon-badge#3]
First of all, thanks for updating the plugin 😃👍 

After your upgrade to 1.0.4 some hours ago, all our builds now get en error message 🤔 

**`##[error]Unhandled: Unexpected token ...`**

![image](https://user-images.githubusercontent.com/5013909/91136614-a7ac3400-e6ae-11ea-9de8-01d952f48624.png)

We get this on both hosted and private agent pipelines, running both on _windows-2019_ and _macOS-10.15_.

**Comment by damienaicheh** [comment]
Hi, thanks for the feedback, curiously the task work perfectly locally on my machine but not correctly online. Pureimage is based on jpeg-js which has breaking changes since version 4.0.0, I suppose the issue is here.  I don't have time to investigate more, I revert to a previous version of pureimage and push a version 1.0.7. Hope it will help you, it's working on my side.

**Comment by Gakk** [comment]
Version 1.0.7 solved the issue.

Once again, @damienaicheh, thanks for the quick response and fix 😃👍
